- name: Upgrade and Update Ubuntu Servers
  hosts: all 
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
      become: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
      become: yes